Add Html, Css and Js fils
naji-97/Review-Project pull request #2
Opened 2022-12-09 13:22 UTC by naji-97

copy index.html, style.css, and index.js from @GraceHttet repo

2022-12-09 14:32 UTC, naji-97 reviewed
While you made a great effort in this project, unfortunately, you still need to configure the Linters
# Invalid Code Review Request
You have submitted a project, that did not pass one of the linters checks. Kindly fix the linter error and submit it again.🙏


Cheers and Happy coding!👏👏👏

2022-12-09 14:32 UTC, naji-97 commented on index.html
> +  </body>
# (Highlights) Good Points: 👍
You documented your work professionally. ✔
GitHub flow is used correctly. ✔

2022-12-09 14:37 UTC, naji-97 commented on css/style.css
> +}
# Optional suggestions
I think it would be better to use classes instead of Id for styling the element

2022-12-12 08:13 UTC, Abenezer-Tilahun requested changes
Hi @naji-97   , 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ Good Job for using [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)

✔️ phrased the comments politely


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

- [ ] Kindly Try to summarize your suggested changes in Good way by highlighting Good points the student addressed and  mention the requested changes in the summary clearly.

_Check the comments below the review._
## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-12 08:13 UTC, Abenezer-Tilahun commented on css/style.css
> +}
- [x] Good job for using [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) and you phrased the comments politely for suggested changes,  But Kindly makes sure that ,you  includes an explanation, a "why", for each requested change.

Ex. "I think it would be better to use `classes  `instead of `Id` for styling the element because when you use `classes` you can assigned to multiple elements on a page or throughout the website,While an `ID` is specific to a single element.

2022-12-12 08:13 UTC, Abenezer-Tilahun commented on index.html
> +  </body>
- [ ] Kindly makes sure that when you used the [GitHub inline comments featu](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request), Please Make sure the you left **the comment under a line or block of code that fits the context the comment is about** in this case you mentioned about documenting the work professional and correctly used of git-hub flow this kind of highlight must be mentioned under summarizing your suggestion .So Kindly comments suggestion related the index file you review.

2022-12-12 08:49 UTC, naji-97 reviewed
# Invalid Code Review Request ❌
You have submitted a project, that has no pull request, please create one and resubmit your project

2022-12-12 08:49 UTC, naji-97 commented on css/style.css
> +}
# Optional suggestion
I think it would be better to use classes instead of Id for styling the element because when you use classes you can assign to multiple elements on a page or throughout the website, While an ID is specific to a single element.

2022-12-12 08:49 UTC, naji-97 commented on index.html
> +</html>
# (Highlights) Good Points: 👍
You documented your work professionally. ✔
GitHub flow is used correctly. ✔

2022-12-12 08:56 UTC, Olamarx approved these changes
Hi @naji-97,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif"/>
## Highlights
- GitHub review feature ✔️ 
- Inline comments ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-12 09:07 UTC, merged